name: camera_store_app
description: Camera Store - Ứng dụng mua sắm máy ảnh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Networking
  dio: ^5.4.3+1

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Routing
  go_router: ^14.2.0

  # Secure Storage (JWT token)
  flutter_secure_storage: ^9.2.2

  # Google Fonts
  google_fonts: ^6.2.1
  webview_flutter: ^4.14.0
  intl: ^0.20.2
  socket_io_client: ^3.1.6
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  geolocator: ^14.0.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
